const $=id=>document.getElementById(id),rad=x=>x*Math.PI/180,deg=x=>x*180/Math.PI;
function P(){return{H:+$('H').value,beta:+$('beta').value,crest:+$('crest').value,toe:+$('toe').value,t1:+$('t1').value,g1:+$('g1').value,c1:+$('c1').value,p1:+$('p1').value,g2:+$('g2').value,c2:+$('c2').value,p2:+$('p2').value,wd:+$('wd').value,gw:+$('gw').value,q:+$('q').value,kh:+$('kh').value,kv:+$('kv').value,method:$('method').value,n:+$('n').value,ns:+$('ns').value,target:+$('target').value}}
function toe(p){return p.crest+p.H/Math.tan(rad(p.beta))}
function width(p){return toe(p)+p.toe}
function gy(x,p){let t=toe(p);if(x<=p.crest)return p.H;if(x<=t)return p.H-Math.tan(rad(p.beta))*(x-p.crest);return 0}
function matAt(y,p){return y>p.H-p.t1?{g:p.g1,c:p.c1,phi:p.p1,name:'1'}:{g:p.g2,c:p.c2,phi:p.p2,name:'2'}}
function sy(x,c){let z=c.R*c.R-(x-c.cx)*(x-c.cx);return z>=0?c.cy-Math.sqrt(z):NaN}
function intersect(cx,cy,R,p){let xs=[],n=600,xm=width(p);for(let i=0;i<=n;i++){let x=xm*i/n,z=R*R-(x-cx)**2;if(z>=0){let y=cy-Math.sqrt(z);if(y>=-1e-6&&y<=gy(x,p)+1e-6)xs.push(x)}}return xs.length>8?{xmin:Math.min(...xs),xmax:Math.max(...xs)}:null}
function slices(c,p){let a=[],w=(c.xmax-c.xmin)/p.ns;for(let i=0;i<p.ns;i++){let xl=c.xmin+i*w,xr=xl+w,x=(xl+xr)/2,yt=gy(x,p),yb=sy(x,c);if(!isFinite(yb)||yb>yt)continue;let h=yt-yb,mid=(yt+yb)/2,m=matAt(mid,p),W=m.g*h*w*(1+p.kv),alpha=Math.atan2(sy(xr,c)-sy(xl,c),w),base=Math.hypot(w,sy(xr,c)-sy(xl,c));let waterElev=p.H-p.wd,u=Math.max(0,(waterElev-yb)*p.gw);W+=p.q*w;W*=1; a.push({i:i+1,x,w,W,alpha,base,u,h,mat:m})}return a}
function fell(a,p){let R=0,D=0;for(let s of a){let phi=rad(s.mat.phi),N=s.W*Math.cos(s.alpha)-s.u*s.base*Math.cos(s.alpha);R+=s.mat.c*s.base+Math.max(0,N)*Math.tan(phi);D+=s.W*Math.sin(s.alpha)}return D>0?R/D:Infinity}
function bishop(a,p){let F=1.3;for(let k=0;k<120;k++){let R=0,D=0;for(let s of a){let phi=rad(s.mat.phi),m=Math.cos(s.alpha)+(Math.sin(s.alpha)*Math.tan(phi))/F;let N=s.W-s.u*s.base*Math.cos(s.alpha);R+=(s.mat.c*s.w+Math.max(0,N)*Math.tan(phi))/Math.max(m,1e-6);D+=s.W*Math.sin(s.alpha)}let seismic=(1+p.kh*Math.abs(Math.sin(Math.PI/2)););let nf=R/Math.max(D+seismic,1e-9);if(Math.abs(nf-F)<1e-6)return nf;F=.55*F+.45*nf}return F}
function evalC(cx,cy,R,p){let i=intersect(cx,cy,R,p);if(!i)return null;let c={cx,cy,R,...i},a=slices(c,p);if(a.length<p.ns*.55)return null;let F=p.method==='bishop'?bishop(a,p):fell(a,p);return isFinite(F)&&F>0&&F<20?{c,a,F}:null}
function search(p){let best=null,arr=[];let n=Math.max(9,Math.round(Math.sqrt(p.n/4))),nr=Math.max(5,Math.round(p.n/(n*n)));for(let ix=0;ix<n;ix++){let cx=-p.H*.5+(p.H*1.1)*ix/(n-1);for(let iy=0;iy<n;iy++){let cy=2+p.H*1.15*iy/(n-1),minR=Math.max(cy+1,3),maxR=Math.hypot(cx-toe(p),cy)+p.H*.7;for(let ir=0;ir<nr;ir++){let R=minR+(maxR-minR)*ir/Math.max(1,nr-1),r=evalC(cx,cy,R,p);if(r){arr.push(r);if(!best||r.F<best.F)best=r}}}}arr.sort((a,b)=>a.F-b.F);return{best,arr:arr.slice(0,150)}}
function axes(canvas){let dpr=devicePixelRatio||1,r=canvas.getBoundingClientRect();canvas.width=r.width*dpr;canvas.height=r.height*dpr;let c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);return[c,r.width,r.height]}
function drawCross(p,r){let[c,W,H]=axes($('cross'));c.clearRect(0,0,W,H);let sx=(W-70)/(width(p)+6),sy=(H-55)/(p.H+6),X=x=>35+x*sx,Y=y=>H-30-y*sy;c.fillStyle='#e9eef1';c.beginPath();c.moveTo(X(0),Y(0));c.lineTo(X(0),Y(p.H));c.lineTo(X(p.crest),Y(p.H));c.lineTo(X(toe(p)),Y(0));c.lineTo(X(width(p)),Y(0));c.closePath();c.fill();c.strokeStyle='#34444f';c.lineWidth=2;c.beginPath();c.moveTo(X(0),Y(p.H));c.lineTo(X(p.crest),Y(p.H));c.lineTo(X(toe(p)),Y(0));c.lineTo(X(width(p)),Y(0));c.stroke();let wy=p.H-p.wd;if(wy>0){c.strokeStyle='#2678b5';c.setLineDash([7,5]);c.beginPath();c.moveTo(X(0),Y(wy));c.lineTo(X(width(p)),Y(wy));c.stroke();c.setLineDash([])}if(r){c.strokeStyle='#b3261e';c.lineWidth=3;c.beginPath();for(let i=0;i<=250;i++){let x=r.c.xmin+(r.c.xmax-r.c.xmin)*i/250,y=syf(x,r.c);if(i===0)c.moveTo(X(x),Y(y));else c.lineTo(X(x),Y(y))}c.stroke()}c.fillStyle='#566570';c.font='11px system-ui';c.fillText('Elevation (m)',8,18);c.fillText('x (m)',W-45,H-10)}
function syf(x,c){return sy(x,c)}
function drawSearch(p,s){let[c,W,H]=axes($('search'));c.clearRect(0,0,W,H);if(!s.best)return;let sx=(W-55)/(width(p)+6),sy0=(H-45)/(p.H+6),X=x=>25+x*sx,Y=y=>H-25-y*sy0;for(let r of s.arr){let q=(r.F-s.arr[0].F)/Math.max(s.arr[s.arr.length-1].F-s.arr[0].F,1e-6);c.strokeStyle=`hsl(${120*(1-q)},65%,45%)`;c.lineWidth=1;c.beginPath();for(let i=0;i<=60;i++){let x=r.c.xmin+(r.c.xmax-r.c.xmin)*i/60,y=sy(x,r.c);if(i===0)c.moveTo(X(x),Y(y));else c.lineTo(X(x),Y(y))}c.stroke()}c.strokeStyle='#111';c.lineWidth=3;c.beginPath();for(let i=0;i<=120;i++){let x=s.best.c.xmin+(s.best.c.xmax-s.best.c.xmin)*i/120,y=sy(x,s.best.c);if(i===0)c.moveTo(X(x),Y(y));else c.lineTo(X(x),Y(y))}c.stroke();c.fillStyle='#17232c';c.font='12px system-ui';c.fillText('Lower FoS surfaces shown darker',15,18)}
function table(a){$('rows').innerHTML='';for(let s of a){let tr=document.createElement('tr');[s.i,s.x.toFixed(2),s.w.toFixed(2),s.mat.name,s.h.toFixed(2),s.W.toFixed(1),deg(s.alpha).toFixed(2),s.u.toFixed(2),s.base.toFixed(2)].forEach(v=>{let td=document.createElement('td');td.textContent=v;tr.append(td)});$('rows').append(tr)}}
function run(p=P()){let s=search(p);if(!s.best){$('fos').textContent='—';$('state').textContent='No valid surface';return}s.best.a.forEach(x=>x.W*=1);$('fos').textContent=s.best.F.toFixed(3);$('state').className=s.best.F>=p.target?'good':s.best.F>=1?'warn':'bad';$('state').textContent=s.best.F>=p.target?'STABLE — TARGET MET':s.best.F>=1?'MARGINAL — BELOW TARGET':'UNSTABLE — FoS < 1.00';$('mout').textContent=p.method==='bishop'?'Simplified Bishop':'Ordinary / Fellenius';$('cout').textContent=`(${s.best.c.cx.toFixed(2)}, ${s.best.c.cy.toFixed(2)}) m`;$('rout').textContent=s.best.c.R.toFixed(2)+' m';$('cand').textContent=s.arr.length+' retained';drawCross(p,s.best);drawSearch(p,s);table(s.best.a);window.lastP=p;window.lastSearch=s}
function sweep(){let base=P(),type=$('param').value,vals=[],fs=[];if(type==='phi')vals=[18,20,22,24,26,28,30,32,34,36,38];if(type==='cohesion')vals=[0,5,10,15,20,25,30,35];if(type==='water')vals=[0,4,8,12,16,20,24,28];if(type==='kh')vals=[0,.02,.04,.06,.08,.10,.12];if(type==='surcharge')vals=[0,10,20,30,40,50,60];for(let v of vals){let p={...base};if(type==='phi'){p.p1=v;p.p2=v}if(type==='cohesion'){p.c1=v;p.c2=v*.6}if(type==='water')p.wd=v;if(type==='kh')p.kh=v;if(type==='surcharge')p.q=v;let r=search(p);vals.length&&fs.push(r.best?r.best.F:NaN)}drawChart(vals,fs,$('param').selectedOptions[0].text)}
function drawChart(x,y,label){let[c,W,H]=axes($('chart'));c.clearRect(0,0,W,H);let px=55,py=30,pw=W-80,ph=H-60,good=[];for(let i=0;i<y.length;i++)if(isFinite(y[i]))good.push(y[i]);if(!good.length)return;let ymin=Math.min(...good,1),ymax=Math.max(...good,1);if(ymax-ymin<.2){ymin-=.1;ymax+=.1}let X=i=>px+i*(pw/(x.length-1)),Y=v=>H-py-(v-ymin)/(ymax-ymin)*ph;c.strokeStyle='#cfd8de';c.beginPath();c.moveTo(px,py);c.lineTo(px,H-py);c.lineTo(W-px/2,H-py);c.stroke();c.strokeStyle='#1261a0';c.lineWidth=2.5;c.beginPath();y.forEach((v,i)=>{if(!isFinite(v))return;if(i===0)c.moveTo(X(i),Y(v));else c.lineTo(X(i),Y(v))});c.stroke();c.fillStyle='#18232c';c.font='11px system-ui';c.fillText(label,px,15);for(let i=0;i<x.length;i++){c.fillText(String(x[i]),X(i)-10,H-10)}c.fillText('FoS',8,py+5)}
$('run').onclick=()=>{let b=$('run');b.disabled=true;b.textContent='Analyzing…';setTimeout(()=>{run();b.disabled=false;b.textContent='Run Analysis'},30)}
$('sweep').onclick=sweep;run();
